#ifndef CAPS_CHAINPARAMSSEEDS_H
#define CAPS_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the caps network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {
    0x01,0x04,0xae,0x04,0x2d,0x21,0x31,0x16,  // 174.4.45.33:12566
};

// Empty testnet seeds - node will use DNS seeds or -addnode
static const uint8_t chainparams_seed_test[] = {0x00};
#endif // CAPS_CHAINPARAMSSEEDS_H
